# Usando Numpy

In [1]:
# Una vez que hayas instalado NumPy puedes importarlo como una biblioteca:
import numpy as np

### Matrices de Numpy

Las matrices de Numpy se presentan básicamente en dos formas: vectores y matrices. Los vectores son matrices estrictamente unidimensionales y las matrices son bidimensionales (pero debes tener en cuenta que una matriz puede tener solo una fila o una columna).

# Creación de matrices de Numpy

### A partir de una lista de Python

Podemos crear una matriz convirtiendo directamente una lista o una lista de listas:

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Métodos integrados

Existen muchas formas integradas de generar matrices

### arange

Devuelve valores espaciados uniformemente dentro de un intervalo determinado.

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generar matrices de ceros o unos.

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones(3)

array([1., 1., 1.])

In [11]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Devuelve números espaciados uniformemente en un intervalo especificado.

In [12]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [13]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

### eye

Crea una matriz de identidad

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Random 

Numpy también tiene muchas formas de crear matrices de números aleatorios:

### rand
Crea una matriz de la forma dada y rellénala con
muestras aleatorias de una distribución uniforme
sobre ``[0, 1]``.

In [14]:
np.random.rand(2)

array([0.68229152, 0.10884392])

In [15]:
np.random.rand(5,5)

array([[0.39656617, 0.47305467, 0.05078131, 0.24536617, 0.46802373],
       [0.59155816, 0.992844  , 0.97402562, 0.73760817, 0.93592716],
       [0.89463913, 0.05286558, 0.17560936, 0.98481722, 0.21539087],
       [0.75812731, 0.53197823, 0.53011996, 0.24746855, 0.56860392],
       [0.21993299, 0.93099257, 0.15886314, 0.04092969, 0.56380813]])

### randn

Devuelve una muestra (o muestras) de la distribución "normal estándar". A diferencia de rand, que es uniforme:

In [17]:
np.random.randn(2)

array([-0.05895846, -0.04870096])

In [18]:
np.random.randn(5,5)

array([[ 1.64258702, -0.82438545, -0.22177283, -2.00020275, -0.30079866],
       [ 1.43622458, -0.70351105,  0.02538447, -0.27851049,  1.13130204],
       [ 1.74708395,  0.28312711,  0.25134602, -0.29013397, -0.10589327],
       [-0.73279293,  0.38884202,  1.39954608,  0.66415704, -1.13344298],
       [ 1.12988158, -0.40505873,  3.07307498,  0.79821096, -1.14334162]])

### randint
Devuelve números enteros aleatorios desde `bajo` (inclusive) hasta `alto` (exclusive).

In [19]:
np.random.randint(1,100)

68

In [20]:
np.random.randint(1,100,10)

array([92, 69, 55, 13, 16, 84, 38, 67, 29, 27])

# Atributos y métodos de matriz

Analicemos algunos atributos y métodos útiles de una matriz:

In [21]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
ranarr

array([32, 32, 40, 48, 35, 22, 48, 26, 34, 18])

# Reshape
Devuelve una matriz que contiene los mismos datos con una nueva forma.

In [24]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

Estos son métodos útiles para encontrar valores máximos o mínimos, o para encontrar sus ubicaciones de índice usando argmin o argmax

In [25]:
ranarr

array([32, 32, 40, 48, 35, 22, 48, 26, 34, 18])

In [26]:
ranarr.max()

48

In [27]:
ranarr.argmax()

3

In [28]:
ranarr.min()

18

In [29]:
ranarr.argmin()

9

# Shape

La forma es un atributo que tienen las matrices (no un método):

In [30]:
# Vector
arr.shape

(25,)

In [31]:
# Observe los dos juegos de corchetes.
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [32]:
arr.reshape(1,25).shape

(1, 25)

In [33]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [34]:
arr.reshape(25,1).shape

(25, 1)

### dtype

También puedes obtener el tipo de datos del objeto en la matriz:

In [36]:
arr.dtype

dtype('int32')

# Indexación y selección de Numpy
En esta lección, analizaremos cómo seleccionar elementos o grupos de elementos de una matriz.

In [37]:
import numpy as np

In [38]:
#Creando una matriz de muestra
arr = np.arange(0,11)

In [39]:
#Mostrar
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Indexación y selección de corchetes
La forma más sencilla de elegir uno o varios elementos de una matriz es muy similar a las listas de Python:

In [40]:
#Obtener un valor en un índice
arr[8]

8

In [41]:
#Obtener valores en un rango
arr[1:5]

array([1, 2, 3, 4])

In [43]:
#Obtener valores en un rango
arr[0:5]

array([0, 1, 2, 3, 4])

# Broadcasting

Las matrices Numpy se diferencian de una lista normal de Python por su capacidad de difusión:

In [44]:
#Establecer un valor con rango de índice (Broadcasting)
arr[0:5]=100

#Mostrar
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [45]:
# Restablecer matriz, veremos por qué tuve que reiniciar en un momento
arr = np.arange(0,11)

#Mostrar
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
#Notas importantes sobre Slices
slice_of_arr = arr[0:6]

#Mostrar porción
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [47]:
#Cambiar porción
slice_of_arr[:]=99

#Mostrar Slice nuevamente
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [48]:
# Ahora observe que los cambios también ocurren en nuestra matriz original!

In [49]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [50]:
#Los datos no se copian, es una vista de la matriz original! ¡Esto evita problemas de memoria!

In [51]:
#Para obtener una copia, debe ser explícito.
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

# Indexación de una matriz 2D (matrices)

El formato general es **arr_2d[row][col]** o **arr_2d[row,col]**. Recomiendo utilizar la notación de coma para mayor claridad.

In [52]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Mostrar
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [53]:
#Fila de indexación
arr_2d[1]


array([20, 25, 30])

In [54]:
# El formato es arr_2d[row][col] o arr_2d[row,col]

# Obtención del valor de cada elemento
arr_2d[1][0]

20

In [55]:
# Obtención del valor de un elemento individual
arr_2d[1,0]

20

In [56]:
# 2D array slicing

#Forma (2,2) desde la esquina superior derecha
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [57]:
#Dar forma a la fila inferior
arr_2d[2]

array([35, 40, 45])

In [58]:
#Dar forma a la fila inferior
arr_2d[2,:]

array([35, 40, 45])

# Indexación sofisticada

La indexación sofisticada le permite seleccionar filas o columnas enteras sin seguir un orden determinado. Para demostrarlo, construyamos rápidamente una matriz numpy:

In [59]:
#Configurar matriz
arr2d = np.zeros((10,10))

In [60]:
#Longitud de la matriz
arr_length = arr2d.shape[1]

In [61]:
#Configurar matriz

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [62]:
#La indexación elegante permite lo siguiente

In [63]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [64]:
#Permite en cualquier orden
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

# Selección

Repasemos brevemente cómo usar corchetes para la selección basada en operadores de comparación.

In [65]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [67]:
bool_arr = arr>4

In [68]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [69]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [70]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [71]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

# Operaciones NumPy

## Aritmética
Puedes realizar fácilmente operaciones aritméticas de matrices con matrices, o operaciones escalares con matrices. Veamos algunos ejemplos:

In [72]:
import numpy as np
arr = np.arange(0,10)

In [73]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [74]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [75]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [76]:
# Advertencia sobre la división por cero, pero no es un error.
# Recién reemplazado por nan
arr/arr

C:\Users\Jhon\AppData\Local\Temp\ipykernel_11484\1113355096.py:3: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [75]:
# También advertencia, pero no un error, sino infinito
1/arr

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [77]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

## Funciones de matriz universales

Numpy incluye muchas [funciones de matriz universales](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), que son básicamente operaciones matemáticas que se pueden utilizar para realizar operaciones en toda la matriz. Veamos algunas de las más comunes:

In [78]:
#Tomando raíces cuadradas
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [79]:
#Calcular exponencial (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [80]:
np.max(arr) #Lo mismo que arr.max()

9

In [81]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [81]:
np.log(arr)

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])